<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>TankStations</AssemblyName>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Assembly-CSharp"><HintPath>../../Ostranauts_Data/Managed/Assembly-CSharp.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine"><HintPath>../../Ostranauts_Data/Managed/UnityEngine.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>../../Ostranauts_Data/Managed/UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.TextMeshPro"><HintPath>../../Ostranauts_Data/Managed/Unity.TextMeshPro.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.UIModule"><HintPath>../../Ostranauts_Data/Managed/UnityEngine.UIModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.UI"><HintPath>../../Ostranauts_Data/Managed/UnityEngine.UI.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="0Harmony"><HintPath>../../BepInEx/core/0Harmony.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="BepInEx"><HintPath>../../BepInEx/core/BepInEx.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
</Project>
